---
- name: kubernees file
  hosts: all
  become: yes
  tasks:
  - name: swap off
    mount: 
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
  - name: repo add
    yum_repository:
      name: kubernetes
      description: kubernetes
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled: yes
      gpgcheck: yes
      repo_gpgcheck: yes
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  - name: insall "{{ item }}"
    yum: 
      name: "{{ item }}"
      state: present
    with_items:
      - docker
      - kubelet
      - kubectl
      - kubeadm
  - name: service "{{ item }}" start
    service: 
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items: 
      - kubelet
      - docker
