- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: kubernetes_join_command
    - debug:
       msg: "{{ kubernetes_join_command.stdout }}"
    - name: Copy join command to local file.
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777

- hosts: node
  remote_user: ansible
  become: yes
  tasks:
   - name: Copy join command to worker nodes.
     become: yes
     copy:
       src: /tmp/kubernetes_join_command
       dest: /tmp/kubernetes_join_command
       mode: 0777   
   - name: Join the Worker nodes with the master.
     become: yes
     command: sh /tmp/kubernetes_join_command
     register: joined_or_not
   - debug:
       msg: "{{ joined_or_not.stdout }}"
